server:
  port: 8080

spring:
  application:
    name: flashodds-backend
  codec:
    max-in-memory-size: 2MB
  threads:
    virtual:
      enabled: true
  webflux:
    base-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

app:
  odds:
    provider: ${ODDS_PROVIDER:mock}
    api-key: ${ODDS_API_KEY:}
    regions: ${ODDS_REGIONS:us}
    markets: ${ODDS_MARKETS:h2h,spreads,totals}
    sports: ${ODDS_SPORTS:nfl,nba,nhl,mlb}
    enrichment-enabled: ${ODDS_ENRICHMENT:true}
    refresh-seconds: ${ODDS_REFRESH:15s}
    cache-ttl-seconds: ${ODDS_CACHE_TTL:60s}
    max-payload-size: 2MB

logging:
  level:
    root: INFO
    com.flashodds.backend: INFO

bucket4j:
  enabled: true
  filters:
    - cache-name: rateLimitCache
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 120
              time: 1
              unit: minutes
