name: Backend Tests

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x backend/mvnw

      - name: Run unit tests
        run: ./backend/mvnw -B test
